version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/alarm-yeelight
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install cmake
      - run:
          name: Initialize Git Submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: Build with cmake
          command: |
            mkdir build
            cd build
            cmake ..
            make
      - run:
          name: Build exclusive with make
          command: |
            cd src
            make
            make clean
workflows:
 version: 2
 build_commits:
   jobs:
     - build
